Repository googleapis/nodejs-iot, pull requests merged in 2019-05, with the labels that each got.

#143 chore: remove Node.js v6 CI
  .kokoro/continuous/node6/common.cfg
  .kokoro/continuous/node6/test.cfg
  .kokoro/presubmit/node6/common.cfg
  .kokoro/presubmit/node6/test.cfg
Labels: cla: yes

#144 build!: upgrade engines field to >=8.10.0
  package.json
Labels: cla: yes

#145 chore: do not run CI on grpc-js
  .kokoro/continuous/node10/system-test-grpcjs.cfg
  .kokoro/presubmit/node10/system-test-grpcjs.cfg
Labels: cla: yes

#148 build: patch Windows container, fixing Node 10
  .kokoro/test.bat
Labels: cla: yes

#149 build: allow Node 10 to push to codecov
  .kokoro/continuous/node10/test.cfg
  .kokoro/continuous/node8/test.cfg
Labels: cla: yes

#150 build: allow Node 10 on presubmit to push to codecov
  .kokoro/presubmit/node10/test.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: cla: yes

#147 build: only pipe to codecov if tests run on Node 10
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/test.sh
  synth.metadata
Labels: cla: yes

#152 fix: DEADLINE_EXCEEDED is no longer retried
  package.json
  src/index.js
  src/v1/device_manager_client.js
  src/v1/device_manager_client_config.json
  src/v1/doc/google/iam/v1/doc_iam_policy.js
  src/v1/doc/google/iam/v1/doc_policy.js
  src/v1/doc/google/type/doc_expr.js
  synth.metadata
Labels: cla: yes

#155 fix: DEADLINE_EXCEEDED retry code is idempotent
  src/v1/device_manager_client_config.json
  synth.metadata
Labels: cla: yes

#158 build: updated kokoro config for coverage and release-please
  .kokoro/continuous/node10/test.cfg
  .kokoro/release-candidate-issue.sh
  .kokoro/release-requested.sh
  .kokoro/release/publish.cfg
  .kokoro/release/release-candidate-issue.cfg
  .kokoro/release/release-requested.cfg
  .kokoro/test.sh
  synth.metadata
Labels: automerge, cla: yes

#162 chore: release 1.0.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#164 refactor: drop dependency on lodash.merge and update links
  package.json
  src/v1/device_manager_client.js
  synth.metadata
Labels: cla: yes

#165 chore: use published jsdoc-baseline package
  package.json
Labels: automerge, cla: yes, kokoro: force-run

#166 build: add configuration for automated doc deployment
  .kokoro/release/docs.cfg
  .kokoro/release/docs.sh
Labels: cla: yes

#167 docs: update quickstart and generate readme
  .cloud-repo-tools.json
  .gitignore
  .readme-partials.yaml
  .repo-metadata.json
  README.md
  package.json
  samples/README.md
  samples/quickstart.js
  synth.metadata
Labels: cla: yes

#168 build: ignore proto files in test coverage
  .nycrc
Labels: cla: yes

#169 fix: shell jobs were outputting too much information
  .kokoro/docs.sh
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline.sh
Labels: cla: yes
