Repository googleapis/nodejs-iot, pull requests merged in 2019-01, with the labels that each got.

#102 fix(docs): remove unused IAM message types
  src/v1/doc/google/cloud/iot/v1/doc_resources.js
  src/v1/doc/google/iam/v1/doc_policy.js
  synth.metadata
Labels: cla: yes

#104 Release @google-cloud/iot v0.2.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#106 chore: update year in the license headers
  smoke-test/device_manager_smoke_test.js
  src/v1/device_manager_client.js
  src/v1/doc/google/cloud/iot/v1/doc_device_manager.js
  src/v1/doc/google/cloud/iot/v1/doc_resources.js
  src/v1/doc/google/iam/v1/doc_iam_policy.js
  src/v1/doc/google/iam/v1/doc_policy.js
  src/v1/doc/google/protobuf/doc_any.js
  src/v1/doc/google/protobuf/doc_empty.js
  src/v1/doc/google/protobuf/doc_field_mask.js
  src/v1/doc/google/protobuf/doc_timestamp.js
  src/v1/doc/google/rpc/doc_status.js
  src/v1/index.js
  synth.metadata
  test/gapic-v1.js
Labels: cla: yes

#107 build: ignore googleapis.com in doc link checker
  .kokoro/docs.sh
Labels: automerge, cla: yes
