Repository googleapis/nodejs-iot, pull requests merged in 2020-08, with the labels that each got.

#381 build: --credential-file-override is no longer required
  .kokoro/populate-secrets.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#382 build: use gapic-generator-typescript v1.0.7
  src/v1/device_manager_client.ts
  synth.metadata
Labels: cla: yes, context: full

#383 chore: update cloud rad kokoro build job
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#385 build: perform publish using Node 12
  .kokoro/release/publish.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#386 refactor: clean up sample test structure
  samples/.eslintrc.yml
  samples/http_example/cloudiot_http_example.js
  samples/http_example/package.json
  samples/http_example/test/cloudiot_http_example.test.js
  samples/manager/package.json
  samples/manager/test/manager.test.js
  samples/mqtt_example/package.json
  samples/mqtt_example/test/cloudiot_mqtt_example.test.js
  samples/package.json
Labels: cla: yes

#387 chore: start tracking obsolete files
  synth.metadata
Labels: automerge, cla: yes, context: full

#390 build: track flaky tests for "nightly", add new secrets for tagging
  .github/publish.yml
  .kokoro/release/publish.cfg
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  synth.metadata
Labels: cla: yes, context: full
