Repository googleapis/nodejs-iot, pull requests merged in 2020-11, with the labels that each got.

#414 build(node): add KOKORO_BUILD_ARTIFACTS_SUBDIR to env
  .kokoro/trampoline_v2.sh
  synth.metadata
Labels: api: cloudiot, automerge, cla: yes, context: full

#416 fix: do not modify options object, use defaultScopes
  package.json
  src/index.ts
  src/v1/device_manager_client.ts
  synth.metadata
  system-test/fixtures/sample/src/index.ts
  system-test/install.ts
Labels: api: cloudiot, automerge, cla: yes

#418 fix(browser): check for fetch on window
  protos/protos.json
  src/v1/device_manager_client.ts
  synth.metadata
Labels: api: cloudiot, cla: yes, context: none

#420 docs: spelling correction for "targetting"
  README.md
  synth.metadata
Labels: api: cloudiot, automerge, cla: yes, context: full
