Repository googleapis/nodejs-iot, pull requests merged in 2020-05, with the labels that each got.

#330 style: correct async structure
  samples/manager/manager.js
Labels: cla: yes

#331 style: correct async structure for setup-iot-topic
  samples/manager/manager.js
Labels: cla: yes

#333 fix: regenerate unit tests
  synth.metadata
  test/gapic_device_manager_v1.ts
Labels: automerge, cla: yes

#336 chore: corrected async structure
  samples/manager/manager.js
Labels: cla: yes

#332 chore: corrected async structure
  samples/manager/manager.js
Labels: automerge, cla: yes

#335 fix: synth.py clean up for multiple version
  src/index.ts
  synth.metadata
  synth.py
Labels: automerge, cla: yes

#338 build: do not fail builds on codecov errors (#528)
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#337 chore: corrected async structure [last part] for manager.js
  samples/http_example/package.json
  samples/manager/manager.js
  samples/manager/package.json
  samples/mqtt_example/cloudiot_mqtt_example_nodejs.js
  samples/mqtt_example/package.json
  samples/package.json
Labels: cla: yes

#340 build: import in protos/protos.js changed
  protos/protos.js
  synth.metadata
Labels: automerge, cla: yes, context: none
