Repository googleapis/nodejs-iot, pull requests merged in 2021-02, with the labels that each got.

#432 chore: update CODEOWNERS config
  .repo-metadata.json
Labels: api: cloudiot, automerge, cla: yes

#433 build: adds UNORDERED_LIST enum
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  synth.metadata
Labels: api: cloudiot, automerge, cla: yes, context: none

#435 chore: use repo metadata to populate nodejs CODEOWNERS
  .github/CODEOWNERS
  synth.metadata
Labels: api: cloudiot, automerge, cla: yes, context: full

#434 docs: add fieldMask format clarification to avoid misunderstandings.
  protos/google/cloud/iot/v1/device_manager.proto
  protos/google/cloud/iot/v1/resources.proto
  src/v1/device_manager_client.ts
  synth.metadata
Labels: api: cloudiot, cla: yes, context: full

#436 fix: add fieldMask for getDevice and listDevices
  samples/manager/manager.js
Labels: api: cloudiot, cla: yes, samples

#438 feat: add serverCertFile parameter
  samples/mqtt_example/README.md
  samples/mqtt_example/cloudiot_mqtt_example_nodejs.js
  samples/mqtt_example/resources/roots.pem
  samples/mqtt_example/test/cloudiot_mqtt_example.test.js
Labels: api: cloudiot, cla: yes, samples
