Repository googleapis/nodejs-iot, pull requests merged in 2021-01, with the labels that each got.

#425 docs: update dates
  .jsdoc.js
  protos/protos.d.ts
  protos/protos.js
  src/v1/device_manager_client.ts
  src/v1/index.ts
  synth.metadata
  system-test/fixtures/sample/src/index.js
  system-test/fixtures/sample/src/index.ts
  system-test/install.ts
  test/gapic_device_manager_v1.ts
Labels: api: cloudiot, automerge, cla: yes, context: none

#426 feat: adds style enumeration
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  synth.metadata
Labels: api: cloudiot, automerge, cla: yes, context: none

#428 chore: add iot team as code owner
  .github/CODEOWNERS
Labels: api: cloudiot, cla: yes

#431 refactor(nodejs): move build cop to flakybot
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline_v2.sh
  synth.metadata
Labels: api: cloudiot, automerge, cla: yes, context: full
